const INTERNAL_SERVER_ERROR = 500;
const NOT_FOUND = 404;
const BAD_REQUEST = 400;
const UNAUTHORIZED = 401;
const ALREADY_EXIST = 409;
const OTHER_MOVIE = 403;

module.exports = {
  INTERNAL_SERVER_ERROR,
  NOT_FOUND,
  BAD_REQUEST,
  UNAUTHORIZED,
  ALREADY_EXIST,
  OTHER_MOVIE,
};
